# Generated by Django 5.0 on 2023-12-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('contenido', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(default='static/post_default.png', upload_to='media')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(default='Sin Categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BlogGrupo1.categoria')),
            ],
            options={
                'ordering': ('fecha_creado',),
            },
        ),
    ]
