# Generated by Django 5.0 on 2023-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogGrupo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='static/categoria/post_default.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='static/post/post_default.png', upload_to='media'),
        ),
    ]
